apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-14T17:30:34Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "8751"
  uid: dd3d55d8-4bec-4d11-b5f5-e0f5123efeb8
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.96.44.25
  clusterIPs:
  - 10.96.44.25
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30723
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
